## Lenguaje que utilizamos, es nuestro taskrunner y es obligatorio
language: go

# Instalamos go, con la versi칩n que usamos en el proyecto
go:
    #Versi칩n que probamos para asegurar compatibilidad hacia adelante
    - beta

    #Versi칩n m치s extendida (LTS)
    - 1.15

# Instalamos el linter
before_install:
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.24.0

# Ejecutamos el linter y los tests
script:
    make lint test