language: go

go:
    - 1.15

# Construimos el contenedor
before_install:
    docker build -t guillelpnz/textanalyzer .

# Ejecutamos nuestro contenedor
script:
    docker run -t -v `pwd`:/test guillelpnz/textanalyzer